# -*- coding: utf-8 -*-
"""Mercado Central 24h - Asistente IA_1.2v.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yqicJtdV3RBxlmLJSvnEuYLfvnidC5UN
"""

import streamlit as st
import os
import glob
import tempfile
import hashlib
import pandas as pd
from dotenv import load_dotenv
from langchain_community.document_loaders import PyPDFLoader
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

load_dotenv()  # lee el archivo .env

# KNOWLEDGE_DIR = os.path.join(os.path.dirname(__file__), "knowledge") # __file__ is not defined in Colab
KNOWLEDGE_DIR = os.path.join(".", "knowledge") # Use current directory for Colab
os.makedirs(KNOWLEDGE_DIR, exist_ok=True)

st.set_page_config(page_title="Mercado Central 24h - Asistente IA", layout="wide", page_icon="🛒")

st.markdown("""
    <style>
    .main { background-color: #0d1117; color: #ffffff; }
    .stApp { background-color: #0f141c; }
    div[data-testid="stSidebar"] { background-color: #161b22; }
    .stChatMessage { border-radius: 12px; margin-bottom: 10px; }
    </style>
""", unsafe_allow_html=True)

# ----------------- BARRA LATERAL -----------------
with st.sidebar:
    st.title("⚙️ Configuración & Archivos")

    proveedores = ["Groq", "Google Gemini", "OpenRouter"]  # Groq primero = por defecto
    proveedor = st.selectbox("Proveedor de IA", proveedores, index=0)

    env_key_map = {
        "Google Gemini": "GOOGLE_API_KEY",
        "Groq": "GROQ_API_KEY",
        "OpenRouter": "OPENROUTER_API_KEY",
    }
    key_from_env = os.environ.get(env_key_map[proveedor], "")

    if proveedor == "Google Gemini":
        api_key = st.text_input("Gemini API Key", value=key_from_env, type="password")
        modelo_seleccionado = st.selectbox("Modelo", ["gemini-2.0-flash", "gemini-1.5-flash"])
    elif proveedor == "Groq":
        api_key = st.text_input("Groq API Key (console.groq.com)", value=key_from_env, type="password")
        modelo_seleccionado = st.selectbox("Modelo", ["llama-3.3-70b-versatile", "llama-3.1-8b-instant", "mixtral-8x7b-32768"])
    elif proveedor == "OpenRouter":
        api_key = st.text_input("OpenRouter API Key (openrouter.ai)", value=key_from_env, type="password")
        modelo_seleccionado = st.selectbox("Modelo", ["meta-llama/llama-3.3-70b-instruct:free", "google/gemini-2.0-flash-exp:free", "deepseek/deepseek-r1:free"])

    if key_from_env:
        st.caption("🔑 API Key cargada desde .env")

    st.markdown("---")
    st.subheader("📂 Base de conocimiento")
    st.caption(f"PDFs fijos en `/knowledge`: se cargan solos al iniciar.")

    archivos_fijos = sorted(
        glob.glob(os.path.join(KNOWLEDGE_DIR, "*.pdf")) +
        glob.glob(os.path.join(KNOWLEDGE_DIR, "*.xlsx")) +
        glob.glob(os.path.join(KNOWLEDGE_DIR, "*.xls"))
    )
    # if archivos_fijos:
    #     st.write("**Archivos fijos detectados:**")
    #     for f in archivos_fijos:
    #         st.write(f"- {os.path.basename(f)}")
    if not archivos_fijos: # Modificado para solo mostrar el mensaje si no hay archivos
        st.info("No hay archivos en /knowledge todavía. Copia tus PDFs/Excel ahí.")

    st.markdown("---")
    st.subheader("➕ Agregar documentos extra (opcional)")
    uploaded_files = st.file_uploader(
        "Sube archivos adicionales (PDF o Excel)",
        type=["pdf", "xlsx", "xls"],
        accept_multiple_files=True
    )
    reprocesar_btn = st.button("🔄 Reconstruir base de conocimiento")

    st.markdown("---")
    st.subheader("💡 Preguntas Frecuentes")
    st.markdown("""
    * ¿Cuáles son las políticas de devolución de Mercado Central 24h?
    * ¿Cómo puedo solicitar un cambio de turno?
    * ¿Qué documentos necesito para una baja médica?
    * ¿Existe un programa de beneficios para empleados?
    * ¿Cómo reporto un incidente de seguridad en la tienda?
    * ¿Cuál es el horario de atención al cliente?
    * ¿Cómo funciona el proceso de inventario?
    * ¿Hay oportunidades de crecimiento profesional?
    * ¿Dónde encuentro el manual de procedimientos?
    * ¿Cómo puedo contactar al departamento de RRHH?
    """)

# ----------------- PROCESAMIENTO RAG -----------------
@st.cache_resource(show_spinner=False)
def inicializar_embeddings():
    return HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")


def cargar_pdf(path_o_bytes, nombre, is_path=True):
    if is_path:
        loader = PyPDFLoader(path_o_bytes)
        return loader.load()
    else:
        with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
            tmp.write(path_o_bytes)
            tmp_path = tmp.name
        loader = PyPDFLoader(tmp_path)
        docs = loader.load()
        os.remove(tmp_path)
        return docs


def cargar_excel_path(path):
    docs = []
    excel_data = pd.read_excel(path, sheet_name=None)
    for sheet_name, df in excel_data.items():
        texto_tabla = df.to_string(index=False)
        docs.append(Document(
            page_content=f"Hoja de inventario ({sheet_name}):\n\n{texto_tabla}",
            metadata={"source": os.path.basename(path), "sheet": sheet_name}
        ))
    return docs


def construir_vectorstore(uploaded_files_extra):
    docs = []

    # 1. PDFs fijos de /knowledge
    for path in sorted(glob.glob(os.path.join(KNOWLEDGE_DIR, "*.pdf"))):
        docs.extend(cargar_pdf(path, os.path.basename(path), is_path=True))

    # 1b. Excel fijos de /knowledge
    for path in sorted(glob.glob(os.path.join(KNOWLEDGE_DIR, "*.xlsx")) + glob.glob(os.path.join(KNOWLEDGE_DIR, "*.xls"))):
        docs.extend(cargar_excel_path(path))

    # 2. Archivos subidos manualmente en esta sesión
    if uploaded_files_extra:
        for file in uploaded_files_extra:
            if file.name.endswith(".pdf"):
                docs.extend(cargar_pdf(file.getvalue(), file.name, is_path=False))
            elif file.name.endswith((".xlsx", ".xls")):
                with tempfile.NamedTemporaryFile(delete=False, suffix=os.path.splitext(file.name)[1]) as tmp:
                    tmp.write(file.getvalue())
                    tmp_path = tmp.name
                excel_data = pd.read_excel(tmp_path, sheet_name=None)
                for sheet_name, df in excel_data.items():
                    texto_tabla = df.to_string(index=False)
                    docs.append(Document(
                        page_content=f"Hoja de inventario ({sheet_name}):\n\n{texto_tabla}",
                        metadata={"source": file.name, "sheet": sheet_name}
                    ))
                os.remove(tmp_path)

    if not docs:
        return None

    text_splitter = RecursiveCharacterTextSplitter(chunk_size=800, chunk_overlap=150)
    chunks = text_splitter.split_documents(docs)
    embeddings = inicializar_embeddings()
    return Chroma.from_documents(chunks, embeddings)


if "vectorstore" not in st.session_state:
    st.session_state.vectorstore = None
if "kb_signature" not in st.session_state: # Agregado para rastrear la firma de la KB
    st.session_state.kb_signature = None

# Firma para saber si hay que reconstruir automáticamente (cambios en /knowledge)
archivos_conocimiento = sorted(
    glob.glob(os.path.join(KNOWLEDGE_DIR, "*.pdf")) +
    glob.glob(os.path.join(KNOWLEDGE_DIR, "*.xlsx")) +
    glob.glob(os.path.join(KNOWLEDGE_DIR, "*.xls")) # Corrección aquí: glob.glob
)
firma_actual = hashlib.md5("".join(archivos_conocimiento).encode()).hexdigest()

if st.session_state.vectorstore is None and firma_actual != "d41d8cd98f00b204e9800998ecf8427e": # d41d8cd98f00b204e9800998ecf8427e es el hash de una cadena vacía
    with st.spinner("Cargando base de conocimiento inicial (PDFs fijos)..."):
        st.session_state.vectorstore = construir_vectorstore(None)
        st.session_state.kb_signature = firma_actual

if reprocesar_btn:
    with st.spinner("Reconstruyendo base de conocimiento..."):
        st.session_state.vectorstore = construir_vectorstore(uploaded_files)
        st.session_state.kb_signature = firma_actual
        st.success("¡Base de conocimientos actualizada con éxito!")

# ----------------- INTERFAZ DE CHAT -----------------
st.title("🛒 Mercado Central 24h - Asistente IA")
st.caption("Pregunta tus dudas sobre políticas, inventario, RRHH y seguridad del supermercado.")

if "messages" not in st.session_state:
    st.session_state.messages = [
        {"role": "assistant", "content": "¡Hola! Soy tu asistente virtual de Mercado Central 24h. ¿En qué puedo ayudarte?"}
    ]

for msg in st.session_state.messages:
    st.chat_message(msg["role"]).write(msg["content"])

if prompt_input := st.chat_input("Ingresa tu pregunta aquí..."):
    if not api_key:
        st.error("Por favor ingresa la API Key en la barra lateral (o configúrala en tu archivo .env).")
    elif not st.session_state.vectorstore:
        st.warning("No hay base de conocimiento cargada. Coloca PDFs en /knowledge o súbelos manualmente y pulsa 'Reconstruir base de conocimiento'.")
    else:
        st.session_state.messages.append({"role": "user", "content": prompt_input})
        st.chat_message("user").write(prompt_input)

        retriever = st.session_state.vectorstore.as_retriever(search_kwargs={"k": 3})

        if proveedor == "Google Gemini":
            os.environ["GOOGLE_API_KEY"] = api_key
            llm = ChatGoogleGenerativeAI(model=modelo_seleccionado, temperature=0)

        elif proveedor == "Groq":
            llm = ChatOpenAI(
                model_name=modelo_seleccionado,
                openai_api_key=api_key,
                openai_api_base="https://api.groq.com/openai/v1",
                temperature=0
            )

        elif proveedor == "OpenRouter":
            llm = ChatOpenAI(
                model_name=modelo_seleccionado,
                openai_api_key=api_key,
                openai_api_base="https://openrouter.ai/api/v1",
                temperature=0,
                default_headers={
                    "HTTP-Referer": "https://localhost:8501",
                    "X-Title": "Mercado Central 24h Assistant"
                }
            )

        sys_prompt = (
            "Eres un asistente virtual experto del supermercado Mercado Central 24h.\n"
            "Responde únicamente usando la información del contexto proporcionado.\n"
            "Sé conciso y directo (máximo 2-3 oraciones).\n\n"
            "Contexto:\n{context}\n\n"
            "Pregunta: {question}"
        )
        prompt_template = ChatPromptTemplate.from_template(sys_prompt)

        def format_docs(docs):
            return "\n\n".join(doc.page_content for doc in docs)

        rag_chain = (
            {"context": retriever | format_docs, "question": RunnablePassthrough()}
            | prompt_template
            | llm
            | StrOutputParser()
        )

        with st.chat_message("assistant"):
            with st.spinner("Buscando en la base de conocimientos..."):
                try:
                    respuesta = rag_chain.invoke(prompt_input)
                    st.write(respuesta)
                    st.session_state.messages.append({"role": "assistant", "content": respuesta})
                except Exception as e:
                    if "429" in str(e) or "RESOURCE_EXHAUSTED" in str(e) or "rate_limit" in str(e).lower():
                        st.error("⏳ Has alcanzado el límite de consultas por minuto de la API seleccionada. Espera un momento e inténtalo de nuevo o cambia de proveedor.")
                    else:
                        st.error(f"Ocurrió un error con el proveedor: {e}")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import os
# import glob
# import tempfile
# import hashlib
# import pandas as pd
# from dotenv import load_dotenv
# from langchain_community.document_loaders import PyPDFLoader
# from langchain_core.documents import Document
# from langchain_text_splitters import RecursiveCharacterTextSplitter
# from langchain_community.vectorstores import Chroma
# from langchain_community.embeddings import HuggingFaceEmbeddings
# from langchain_google_genai import ChatGoogleGenerativeAI
# from langchain_openai import ChatOpenAI
# from langchain_core.prompts import ChatPromptTemplate
# from langchain_core.output_parsers import StrOutputParser
# from langchain_core.runnables import RunnablePassthrough
# 
# load_dotenv()  # lee el archivo .env
# 
# # Establece las claves de API como variables de entorno al inicio de la aplicación
# os.environ["GOOGLE_API_KEY"] = "AQ.Ab8RN6Kf95freKP6fWYX_nxSrl4qhdY5S4GoxZKqDQEi_H03pA"
# os.environ["GROQ_API_KEY"] = "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"
# os.environ["OPENROUTER_API_KEY"] = "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"
# 
# KNOWLEDGE_DIR = os.path.join(".", "knowledge") # Use current directory for Colab
# os.makedirs(KNOWLEDGE_DIR, exist_ok=True)
# 
# st.set_page_config(page_title="Mercado Central 24h - Asistente IA", layout="wide", page_icon="🛒")
# 
# st.markdown("""
#     <style>
#     .main { background-color: #0d1117; color: #ffffff; }
#     .stApp { background-color: #0f141c; }
#     div[data-testid="stSidebar"] { background-color: #161b22; }
#     .stChatMessage { border-radius: 12px; margin-bottom: 10px; }
#     </style>
# """, unsafe_allow_html=True)
# 
# # ----------------- BARRA LATERAL -----------------
# with st.sidebar:
#     st.title("⚙️ Configuración & Archivos")
# 
#     proveedores = ["Groq", "Google Gemini", "OpenRouter"]  # Groq primero = por defecto
#     proveedor = st.selectbox("Proveedor de IA", proveedores, index=0)
# 
#     env_key_map = {
#         "Google Gemini": "GOOGLE_API_KEY",
#         "Groq": "GROQ_API_KEY",
#         "OpenRouter": "OPENROUTER_API_KEY",
#     }
#     api_key = os.environ.get(env_key_map[proveedor], "") # Obtener la API key de las variables de entorno
# 
#     if proveedor == "Google Gemini":
#         modelo_seleccionado = st.selectbox("Modelo", ["gemini-2.0-flash", "gemini-1.5-flash"])
#     elif proveedor == "Groq":
#         modelo_seleccionado = st.selectbox("Modelo", ["llama-3.3-70b-versatile", "llama-3.1-8b-instant", "mixtral-8x7b-32768"])
#     elif proveedor == "OpenRouter":
#         modelo_seleccionado = st.selectbox("Modelo", ["meta-llama/llama-3.3-70b-instruct:free", "google/gemini-2.0-flash-exp:free", "deepseek/deepseek-r1:free"])
# 
#     st.markdown("---")
#     st.subheader("📂 Base de conocimiento")
#     st.caption(f"PDFs fijos en `/knowledge`: se cargan solos al iniciar.")
# 
#     archivos_fijos = sorted(
#         glob.glob(os.path.join(KNOWLEDGE_DIR, "*.pdf")) +
#         glob.glob(os.path.join(KNOWLEDGE_DIR, "*.xlsx")) +
#         glob.glob(os.path.join(KNOWLEDGE_DIR, "*.xls"))
#     )
#     # if archivos_fijos:
#     #     st.write("**Archivos fijos detectados:**")
#     #     for f in archivos_fijos:
#     #         st.write(f"- {os.path.basename(f)}")
#     if not archivos_fijos: # Modificado para solo mostrar el mensaje si no hay archivos
#         st.info("No hay archivos en /knowledge todavía. Copia tus PDFs/Excel ahí.")
# 
#     st.markdown("---")
#     st.subheader("➕ Agregar documentos extra (opcional)")
#     uploaded_files = st.file_uploader(
#         "Sube archivos adicionales (PDF o Excel)",
#         type=["pdf", "xlsx", "xls"],
#         accept_multiple_files=True
#     )
#     reprocesar_btn = st.button("🔄 Reconstruir base de conocimiento")
# 
#     st.markdown("---")
#     st.subheader("💡 Preguntas Frecuentes")
#     st.markdown("""
#     * ¿Cuál es el procedimiento para presentar una queja en Mercado Central 24h?
#     * ¿Cómo se resuelve un problema con un producto comprado en el supermercado?
#     * ¿Qué tipo de evidencia se requiere para presentar una queja?
#     * ¿Cuánto tiempo tarda en responderse a una queja presentada en el supermercado?
#     * ¿Puedo solicitar que mi queja sea escalada a PROFECO?
#     * ¿Cómo se manejan las situaciones de tensión con los clientes en Mercado Central 24h?
#     * ¿Qué tipo de capacitación reciben los colaboradores para manejar quejas de clientes?
#     * ¿Cuál es el objetivo de la empatía en la resolución de quejas en el supermercado?
#     * ¿Cómo se prioriza la resolución de quejas en Mercado Central 24h?
#     * ¿Qué información se requiere para presentar una queja en el supermercado?
#     """)
# 
# # ----------------- PROCESAMIENTO RAG -----------------
# @st.cache_resource(show_spinner=False)
# def inicializar_embeddings():
#     return HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
# 
# 
# def cargar_pdf(path_o_bytes, nombre, is_path=True):
#     if is_path:
#         loader = PyPDFLoader(path_o_bytes)
#         return loader.load()
#     else:
#         with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
#             tmp.write(path_o_bytes)
#             tmp_path = tmp.name
#         loader = PyPDFLoader(tmp_path)
#         docs = loader.load()
#         os.remove(tmp_path)
#         return docs
# 
# 
# def cargar_excel_path(path):
#     docs = []
#     excel_data = pd.read_excel(path, sheet_name=None)
#     for sheet_name, df in excel_data.items():
#         texto_tabla = df.to_string(index=False)
#         docs.append(Document(
#             page_content=f"Hoja de inventario ({sheet_name}):\n\n{texto_tabla}",
#             metadata={"source": os.path.basename(path), "sheet": sheet_name}
#         ))
#     return docs
# 
# 
# def construir_vectorstore(uploaded_files_extra):
#     docs = []
# 
#     # 1. PDFs fijos de /knowledge
#     for path in sorted(glob.glob(os.path.join(KNOWLEDGE_DIR, "*.pdf"))):
#         docs.extend(cargar_pdf(path, os.path.basename(path), is_path=True))
# 
#     # 1b. Excel fijos de /knowledge
#     for path in sorted(glob.glob(os.path.join(KNOWLEDGE_DIR, "*.xlsx")) + glob.glob(os.path.join(KNOWLEDGE_DIR, "*.xls"))):
#         docs.extend(cargar_excel_path(path))
# 
#     # 2. Archivos subidos manualmente en esta sesión
#     if uploaded_files_extra:
#         for file in uploaded_files_extra:
#             if file.name.endswith(".pdf"):
#                 docs.extend(cargar_pdf(file.getvalue(), file.name, is_path=False))
#             elif file.name.endswith((".xlsx", ".xls")):
#                 with tempfile.NamedTemporaryFile(delete=False, suffix=os.path.splitext(file.name)[1]) as tmp:
#                     tmp.write(file.getvalue())
#                     tmp_path = tmp.name
#                 excel_data = pd.read_excel(tmp_path, sheet_name=None)
#                 for sheet_name, df in excel_data.items():
#                     texto_tabla = df.to_string(index=False)
#                     docs.append(Document(
#                         page_content=f"Hoja de inventario ({sheet_name}):\n\n{texto_tabla}",
#                         metadata={"source": file.name, "sheet": sheet_name}
#                     ))
#                 os.remove(tmp_path)
# 
#     if not docs:
#         return None
# 
#     text_splitter = RecursiveCharacterTextSplitter(chunk_size=800, chunk_overlap=150)
#     chunks = text_splitter.split_documents(docs)
#     embeddings = inicializar_embeddings()
#     return Chroma.from_documents(chunks, embeddings)
# 
# 
# if "vectorstore" not in st.session_state:
#     st.session_state.vectorstore = None
# if "kb_signature" not in st.session_state:
#     st.session_state.kb_signature = None
# 
# # Firma para saber si hay que reconstruir automáticamente (cambios en /knowledge)
# archivos_conocimiento = sorted(
#     glob.glob(os.path.join(KNOWLEDGE_DIR, "*.pdf")) +
#     glob.glob(os.path.join(KNOWLEDGE_DIR, "*.xlsx")) +
#     glob.glob(os.path.join(KNOWLEDGE_DIR, "*.xls"))
# )
# firma_actual = hashlib.md5("".join(archivos_conocimiento).encode()).hexdigest()
# 
# if st.session_state.vectorstore is None and firma_actual != "d41d8cd98f00b204e9800998ecf8427e":
#     with st.spinner("Cargando base de conocimiento inicial (PDFs fijos)..."):
#         st.session_state.vectorstore = construir_vectorstore(None)
#         st.session_state.kb_signature = firma_actual
# 
# if reprocesar_btn:
#     with st.spinner("Reconstruyendo base de conocimiento..."):
#         st.session_state.vectorstore = construir_vectorstore(uploaded_files)
#         st.session_state.kb_signature = firma_actual
#         st.success("¡Base de conocimientos actualizada con éxito!")
# 
# # ----------------- INTERFAZ DE CHAT -----------------
# st.title("🛒 Mercado Central 24h - Asistente IA")
# st.caption("Pregunta tus dudas sobre políticas, inventario, RRHH y seguridad del supermercado.")
# 
# if "messages" not in st.session_state:
#     st.session_state.messages = [
#         {"role": "assistant", "content": "¡Hola! Soy tu asistente virtual de Mercado Central 24h. ¿En qué puedo ayudarte?"}
#     ]
# 
# for msg in st.session_state.messages:
#     st.chat_message(msg["role"]).write(msg["content"])
# 
# if prompt_input := st.chat_input("Ingresa tu pregunta aquí..."):
#     if not api_key:
#         st.error("Por favor ingresa la API Key en la barra lateral (o configúrala en tu archivo .env).")
#     elif not st.session_state.vectorstore:
#         st.warning("No hay base de conocimiento cargada. Coloca PDFs en /knowledge o súbelos manualmente y pulsa 'Reconstruir base de conocimiento'.")
#     else:
#         st.session_state.messages.append({"role": "user", "content": prompt_input})
#         st.chat_message("user").write(prompt_input)
# 
#         retriever = st.session_state.vectorstore.as_retriever(search_kwargs={"k": 3})
# 
#         if proveedor == "Google Gemini":
#             os.environ["GOOGLE_API_KEY"] = api_key
#             llm = ChatGoogleGenerativeAI(model=modelo_seleccionado, temperature=0)
# 
#         elif proveedor == "Groq":
#             llm = ChatOpenAI(
#                 model_name=modelo_seleccionado,
#                 openai_api_key=api_key,
#                 openai_api_base="https://api.groq.com/openai/v1",
#                 temperature=0
#             )
# 
#         elif proveedor == "OpenRouter":
#             llm = ChatOpenAI(
#                 model_name=modelo_seleccionado,
#                 openai_api_key=api_key,
#                 openai_api_base="https://openrouter.ai/api/v1",
#                 temperature=0,
#                 default_headers={
#                     "HTTP-Referer": "https://localhost:8501",
#                     "X-Title": "Mercado Central 24h Assistant"
#                 }
#             )
# 
#         sys_prompt = (
#             "Eres un asistente virtual experto del supermercado Mercado Central 24h.\n"
#             "Responde únicamente usando la información del contexto proporcionado.\n"
#             "Sé conciso y directo (máximo 2-3 oraciones).\n\n"
#             "Contexto:\n{context}\n\n"
#             "Pregunta: {question}"
#         )
#         prompt_template = ChatPromptTemplate.from_template(sys_prompt)
# 
#         def format_docs(docs):
#             return "\n\n".join(doc.page_content for doc in docs)
# 
#         rag_chain = (
#             {"context": retriever | format_docs, "question": RunnablePassthrough()}
#             | prompt_template
#             | llm
#             | StrOutputParser()
#         )
# 
#         with st.chat_message("assistant"):
#             with st.spinner("Buscando en la base de conocimientos..."):
#                 try:
#                     respuesta = rag_chain.invoke(prompt_input)
#                     st.write(respuesta)
#                     st.session_state.messages.append({"role": "assistant", "content": respuesta})
#                 except Exception as e:
#                     if "429" in str(e) or "RESOURCE_EXHAUSTED" in str(e) or "rate_limit" in str(e).lower():
#                         st.error("⏳ Has alcanzado el límite de consultas por minuto de la API seleccionada. Espera un momento e inténtalo de nuevo o cambia de proveedor.")
#                     else:
#                         st.error(f"Ocurrió un error con el proveedor: {e}")

# Crear el directorio 'knowledge' si no existe
import os
os.makedirs('knowledge', exist_ok=True)

print("Los siguientes archivos se encontraron en '/content/':")
!ls -F /content/

print("\nPor favor, identifica en la lista anterior los nombres exactos de tus archivos de conocimiento (PDFs, Excels e 'inventario') y dímelos para que pueda moverlos correctamente a la carpeta 'knowledge'.")
print("Por ejemplo, si ves 'mi_documento.pdf' y 'datos_inventario.xlsx', puedes responder: 'mi_documento.pdf datos_inventario.xlsx inventario'")

# Mover los archivos a la carpeta 'knowledge' con nombres descriptivos
!mv /content/b9abdeaf-ffcb-46c4-8e1b-16935a594875.pdf knowledge/politicas_empresa_1.pdf
!mv /content/c0a37625-c8ee-44f2-885f-7b30480d3017.pdf knowledge/politicas_empresa_2.pdf
!mv /content/e4dc3cc4-55d5-453b-bc68-3f5ef090fc7f.xlsx knowledge/gestion_empleados.xlsx
!mv /content/ed99ddc6-bead-47fd-886b-c007c7e36885.pdf knowledge/manual_seguridad.pdf
!mv /content/6ce88d4f-3c95-42c3-aef3-c156e859f000.pdf knowledge/manual_operaciones.pdf
!mv /content/inventario.xlsx knowledge/inventario_actual.xlsx

# 'Capture.JPG' no se moverá automáticamente ya que el sistema RAG actual solo procesa PDF y Excel.
# Si deseas integrar imágenes, necesitaríamos una estrategia diferente (por ejemplo, OCR o VLM).

print("Archivos de conocimiento movidos a la carpeta 'knowledge'.")

# Instala las dependencias necesarias directamente en el entorno que ejecutará Streamlit
!pip install -q pyngrok streamlit pandas python-dotenv langchain-community langchain-core langchain-text-splitters langchain-google-genai langchain-openai pypdf openpyxl chromadb

# Si tienes un token de autenticación de ngrok, ingrésalo aquí:
from pyngrok import ngrok
ngrok.set_auth_token("3GmiTutv6yv8ZxOkYS8qttCqCpm_5ymNfBndA2j3hyP9rszwL")

# Ejecuta la aplicación Streamlit
print("Iniciando Streamlit...")
!streamlit run app.py &>/dev/null&

# Exponer el puerto 8501 (donde Streamlit se ejecuta por defecto) a través de ngrok
public_url = ngrok.connect(addr="8501", proto="http")
print(f"Tu aplicación Streamlit está disponible en: {public_url}")
print("Por favor, si te sigue dando un error, reinicia el entorno de ejecución (Runtime -> Restart runtime) y ejecuta TODAS las celdas de nuevo.")